OPENAI_API_KEY = ""
GITHUB_TOKEN = ""
GITHUB_URL = "https://github.com/Pseudo-Lab"
QUERY = "JobPT 레포에서 최신 커밋에 대해 요약 설명해줘"
BLOG_URL = "https://day-to-day.tistory.com/"
BLOG_QUERY = "이 블로그의 글들을 읽고 어떤 사람인지 알려주고 어떤 글들을 주로 썼는지 분석해줘."